version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
      POSTGRES_DATABASE: homeassistant
    volumes:
      - /volume1/docker/homeassistant/.postgres:/var/lib/postgresql/data
      - /volume1/docker/homeassistant/db-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - /etc/localtime:/etc/localtime:ro

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.1
    restart: unless-stopped
    network_mode: host
    environment:
      INFLUXDB_DB: homeassistant
      INFLUXDB_USER: homeassistant
      INFLUXDB_USER_PASSWORD: homeassistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/homeassistant/.influxdb:/var/lib/influxdb

  grafana:
    depends_on:
      - influxdb
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: host
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - /volume1/docker/homeassistant/.grafana:/var/lib/grafana

  homeassistant:
    depends_on:
      - postgres
      - influxdb
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    restart: always
    privileged: true
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    network_mode: host
    volumes:
      - /volume1/docker/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
    - TZ=Europe/Oslo
