version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    network_mode: host
    environment:
      POSTGRES_USER: homeassistant
      POSTGRES_PASSWORD: homeassistant
      POSTGRES_DATABASE: homeassistant
    volumes:
      - /home/pi/homeassistant/.postgres:/var/lib/postgresql/data
      - /home/pi/homeassistant/db-init.sh:/docker-entrypoint-initdb.d/01-init.sh
      - /etc/localtime:/etc/localtime:ro

  influxdb:
    container_name: influxdb
    image: influxdb:1.7.1
    restart: unless-stopped
    network_mode: host
    environment:
      INFLUXDB_DB: homeassistant
      INFLUXDB_USER: homeassistant
      INFLUXDB_USER_PASSWORD: homeassistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/homeassistant/.influxdb:/var/lib/influxdb

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    restart: always
    network_mode: host
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
    volumes:
      - /home/pi/homeassistant/.grafana:/var/lib/grafana

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - /home/pi/homeassistant/.zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Oslo

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: always
    network_mode: host
    volumes:
      - /home/pi/homeassistant/mosquitto.conf:/mosquitto/config/mosquitto.conf

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    depends_on:
      - postgres
      - influxdb
      - zigbee2mqtt
    restart: always
    privileged: true
    command: [ "python", "-m", "homeassistant", "--config", "/config", "--log-rotate-days", '3' ]
    network_mode: host
    volumes:
      - /home/pi/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Oslo

  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - /home/pi/homeassistant/.esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
