
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# logger: 
#   logs: 
#     homeassistant.components.<component>: debug

light:
  - platform: switch
    name: shelf
    entity_id: switch.shelf
  # - platform: group
  #   name: Living Room - All
  #   entities:
  #     - light.living_room_roof
  #     - light.living_room_shelf
  #     - light.living_room_window

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


